codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "80...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        base: auto
        flags:
          - unittests
        paths:
          - "!vendor/"
          - "!sandbox/"
          - "!demo/"
          
    patch:
      default:
        target: 80%
        threshold: 5%
        base: auto
        
comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "vendor/**/*"
  - "sandbox/**/*"
  - "demo/**/*"
  - "**/*_test.go"
  - "**/testdata/**/*"
  - "test/fixtures/**/*"
  - "cmd/*/main.go"